---
abstract: 'Japanese Prefectures Data.'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom@gmail.comE<gt>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geography-JapanesePrefectures
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Geography::JapanesePrefectures:
    file: lib/Geography/JapanesePrefectures.pm
    version: 0.10
  Geography::JapanesePrefectures::Unicode:
    file: lib/Geography/JapanesePrefectures/Unicode.pm
    version: 0
requires:
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
