---
abstract: 'Japanese Prefectures Data.'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geography-JapanesePrefectures
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Geography::JapanesePrefectures:
    file: lib/Geography/JapanesePrefectures.pm
    version: 0.11
  Geography::JapanesePrefectures::Unicode:
    file: lib/Geography/JapanesePrefectures/Unicode.pm
requires:
  perl: 5.008001
resources:
  bugtracker: https://github.com/tokuhirom/Geography-JapanesePrefectures/issues
  homepage: https://github.com/tokuhirom/Geography-JapanesePrefectures
  repository: git://github.com/tokuhirom/Geography-JapanesePrefectures.git
version: 0.11
x_contributors:
  - 'otsune <otsune@d0d07461-0603-4401-acd4-de1884942a52>'
  - 'tokuhirom <tokuhirom@d0d07461-0603-4401-acd4-de1884942a52>'
  - 'Atsushi Kobayashi <nekokak@gmail.com>'
